[project]
name = "dc-eda"
version = "0.1.0"
description = "Exploratory Data Analysis for drug combinations in DISNET"
authors = [
    { name = "Joaquin Negrete", email = "joaquin.negrete03@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []
